[marker]
type = "my_aruco"

enable_correction = true
gray_thresh = 125
expand_scale = 1.2
enable_filterby_area = 1
min_r = 20
max_r = 60

enable_filterby_gray = 1
min_gray_thresh = 0
max_gray_thresh = 150

enable_filterby_circularity = 1
min_circularity = 0.8
max_circularity = 1

enable_filterby_convexity = 1
min_convexity = 0.8
max_convexity = 1

enable_filterby_inertiaradio = 1
min_inertiaradio = 0.2
max_inertiaradio = 1

eps_scale = 10
min_samples = 3

